apiVersion: v1
kind: Service
metadata:
  name: spring-boot-docker-k8s-service
spec:
  type: LoadBalancer
  selector:
    app: spring-boot-docker-k8s-deployment-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9999